---
#ftp server has all downloads available but get_url module not working reliably with ftp (June 2017)
#ftp://ftp.nrg.wustl.edu/pub/xnat/

#use for remote targets
#- name: "Download XNAT-{{ xnat_version }} snapshot .war directly to Tomcat webapps folder"
#  get_url: 
#    url=https://bitbucket.org/xnatdev/xnat-web/downloads/{{ xnat.tarball }} 
#    dest=/var/lib/tomcat{{ tomcat_version }}/webapps/ROOT.war
#    force=no 
#    timeout=30
#    tmp_dest=/tmp

#use for local targets e.g. vagrant boxes
- name: "Copy over local {{ xnat.tarball }} to target Tomcat webapps folder (Debian.)"
  copy:
    src=~/Downloads/{{ xnat.tarball }}
    dest=/var/lib/tomcat{{ tomcat_version }}/webapps/ROOT.war
  when: ansible_os_family == 'Debian'

- name: "Copy over local {{ xnat.tarball }} to target Tomcat webapps folder (RedHat.)"
  copy:
    src=~/Downloads/{{ xnat.tarball }}
    dest=/usr/share/tomcat{{ tomcat_version }}/webapps/ROOT.war
  when: ansible_os_family == 'RedHat'

- name: "Add system user {{ tomcat.user }}"
  user: name={{ tomcat.user }} shell=/bin/bash 

- name: "Setup XNAT data directories"
  file: path="{{ xnat_root }}/{{ item }}" group={{ tomcat.group }} owner={{ tomcat.user }} state=directory
  with_items:
      - build
      - archive
      - prearchive
      - cache
      - ftp
      - pipeline
      - home 
      - home/config
      - home/logs
      - home/plugins
      - home/work
      - home/downloads

- name: "Copy xnat-config.properties"
  template: src=xnat-conf.properties.j2 dest={{ xnat_home }}/config/xnat-conf.properties owner={{ tomcat.user }} group={{ tomcat.group }} mode=0644 force=yes

- name: "Check XNAT directory permissions"
  file: path={{ xnat_root }} group={{ tomcat.group }} owner={{ tomcat.user }} recurse=yes

- name: "Create XNAT PostgreSQL user"
  postgresql_user: name={{ xnat.pg_user }} password={{ xnat.pg_password }}

- name: "Create XNAT PostgreSQL db"
  postgresql_db: name={{ xnat.pg_database }} owner={{ xnat.pg_user }}

#- name: Install pip
#  package: name=python-pip state=latest use=apt

#- name: "Install github3 pip package"
#  pip: name=github3.py version=1.0.0a4 state=present

#- name: "Fetch latest Github release tag"
#  github_release:
#    token: "{{ vault_github_token }}"
#    user: "BioMedIA"
#    repo: "xnat-plugins"
#    action: "latest_release"
#  register: result

- name: "Download plugins from latest release"
  get_url:
    dest: "{{ xnat_root }}/home/plugins/"
    url: "https://github.com/BioMedIA/xnat-plugins/releases/download/{{ plugins_release_tag }}/{{ item }}-plugin-{{ plugins_release_tag }}.jar"
  with_items:
        - DownloadWholeProject
        - Frontend
        - UserAttributes
  notify: restart tomcat
